### ISSUE TITLE
How to append pupeteer config option?

### ISSUE THREAD

**Issue by RidaAyed** [timofurrer/pandoc-mermaid-filter#2]
Hi
 
@timofurrer how can I add the `-p puppeteer-config.json` as outlined in https://github.com/mermaidjs/mermaid.cli

Using this option I can get rid of the sandbox issue. E.g. This works:  

`mmdc -p puppeteer-config.json -i flowchart.mmd -o output.svg`

**Comment by barskern** [comment]
Hi,

I managed to append a custom puppeteer config by changing the following [this line](https://github.com/timofurrer/pandoc-mermaid-filter/blob/bdb1d7870879d31503873f3a38a71963965587a4/pandoc_mermaid_filter.py#L31) to include `-p /absolute/path/to/puppeteer-config.json`.

The line should then look like this:

```python
subprocess.check_call([MERMAID_BIN, "-p", "/absolute/path/to/puppeteer-config.json`", "-i", src, "-o", dest])
```

In the puppeteer-config file I have:
```json
{
  "args": ["--no-sandbox"]
}
```

This is a clumsy but simple solution. I was thinking about sending a PR so that this could be set through an environment variable. It should only be a few lines of code.

**Comment by barskern** [comment]
Created a pull request now @RidaAyed, see #4.
